title: Goldendoodles
author: Avery Elliott
email: averyhopeelliott@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Goldendoodles are a highly sought after breed of dog. 
  They are hypo-allergetic, and incredibly loyal to the family.
  They are amazing with kids.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
